[default]
extend-ignore-identifiers-re = [
    # *sigh* this just isn't worth the cost of fixing
    "AttributeID.*Supress.*",
]

[default.extend-identifiers]
# *sigh* this just isn't worth the cost of fixing
AttributeIDSupressMenu = "AttributeIDSupressMenu"

[default.extend-words]
# Don't correct the surname "Teh"
teh = "teh"
Hashi = "Hashi"
consts = "consts"

[files]
extend-exclude = ["**/*.js", "**/*.css", "**/*.html", "examples/*/static/**/*.*"]