[package]
name = "example-unix-socket"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
salvo = { workspace = true, features = ["serve-static", "unix"] }
tokio = { workspace = true, features = ["macros"] }
