[package]
name = "example-static-embed-files"
version.workspace = true
edition.workspace = true
publish.workspace = true


[dependencies]
rust-embed.workspace = true
salvo = { workspace = true, features = ["serve-static"] }
tokio = { workspace = true, features = ["macros"] }
tracing.workspace = true
tracing-subscriber.workspace = true
