[package]
name = "example-static-embed-files"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
rust-embed = "6"
salvo = { workspace = true, features = ["serve-static"] }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
