[package]
name = "example-db-postgres-sqlx"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
salvo = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing.workspace = true
tracing-subscriber.workspace = true
once_cell.workspace = true
sqlx = { version = "0.7", features = [ "runtime-tokio-native-tls" , "postgres" ] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true