[package]
name = "example-catch-error"
version.workspace = true
edition.workspace = true
publish.workspace = true


[dependencies]
anyhow.workspace = true
eyre.workspace = true
salvo = { workspace = true, features = ["anyhow", "eyre"] }
tokio = { workspace = true, features = ["macros"] }
tracing.workspace = true
tracing-subscriber.workspace = true
