[package]
name = "example-extract-data"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
salvo = { path = "../../crates/salvo" }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
