[package]
name = "example-tls-openssl-reload"
version.workspace = true
edition.workspace = true
publish.workspace = true


[dependencies]
async-stream.workspace = true
salvo = { workspace = true, features = ["openssl"] }
tokio = { workspace = true, features = ["macros"] }
tracing.workspace = true
tracing-subscriber.workspace = true
