[package]
name = "example-jwt-auth"
version.workspace = true
edition.workspace = true
publish.workspace = true


[dependencies]
anyhow = "1"
jsonwebtoken.workspace = true
salvo = { workspace = true, features = ["anyhow", "jwt-auth"] }
serde = "1"
time.workspace = true
tokio = { workspace = true, features = ["macros"] }
tracing.workspace = true
tracing-subscriber.workspace = true
