[package]
name = "example-jwt-auth"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
anyhow = "1"
jsonwebtoken = "8.0"
salvo = { path = "../../crates/salvo", features = ["anyhow", "jwt-auth"] }
serde = "1"
time = "0.3"
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
