[package]
name = "example-ws-chat"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
futures-util = { version = "0.3", default-features = false }
once_cell = "1"
salvo = { path = "../../crates/salvo", features = ["ws"] }
tokio = { version = "1", features = ["macros"] }
tokio-stream = { version = "0.1", features = ["net"] }
tracing = "0.1"
tracing-subscriber = "0.3"
