[package]
name = "example-oapi-todos"
version.workspace = true
edition.workspace = true
publish.workspace = true


[dependencies]
salvo = { workspace = true, features = ["oapi"] }
serde = { workspace = true, features = ["derive"] }
serde_json = "1"
tokio = { workspace = true, features = ["macros"] }
compact_str = { version = "0.7", features = ["serde"] }
tracing.workspace = true
tracing-subscriber.workspace = true