[package]
name = "example-with-tower"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
salvo = { workspace = true, features = ["tower-compat"] }
tokio = { workspace = true, features = ["macros"] }
tower = { workspace = true , features = ["limit"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }