[package]
name = "example-with-tower"
version.workspace = true
edition.workspace = true
publish.workspace = true


[dependencies]
salvo = { workspace = true, features = ["tower-compat"] }
tokio = { workspace = true, features = ["macros"] }
tower = { version = "0.4", features = ["limit"] }
tracing.workspace = true
tracing-subscriber.workspace = true
