[package]
edition = "2021"
name = "mysql-rbatis"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rbatis = { version = "4.0" }
salvo = { path = "../../salvo" }
serde = { version = "1.0.133" }
