[package]
name = "example-db-graphql"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
parking_lot = "0.12"
salvo = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing = "^0.1"
tracing-subscriber = "^0.3"
juniper  = "^0.15.10"