[workspace]
members = ["*"]
exclude = ["work-with-tower", "db-prisma-orm", "with-listenfd", "ws-chat-with-salvo-websocket"]

[workspace.package]
version = "0.38.0"
authors = ["Chrislearn Young <chrislearn@hotmail.com>"]
edition = "2021"
rust-version = "1.64"
description = """
Salvo is a powerful and simple Rust web server framework.
"""
homepage = "https://salvo.rs"
repository = "https://github.com/salvo-rs/salvo"
documentation = "https://docs.rs/salvo/"
readme = "./README.md"
keywords = ["http", "async", "web", "framework", "server"]
license = "MIT OR Apache-2.0"
categories = ["web-programming::http-server", "web-programming::websocket", "network-programming", "asynchronous"]

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
eyre = "0.6"
futures-util = "0.3"
once_cell = "1"
parking_lot = "0.12"
salvo = { path = "../crates/salvo", default-features = true }
serde = "1"
serde_json = "1"
thiserror = "1"
tokio = "1"
tracing-subscriber = { version = "0.3" }
tracing = "0.1"
tracing-test = "0.2.1"
url = "2"
chrono = "0.4"
sqlx = "0.6"
