[package]
name = "example-db-mongodb"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
salvo = { workspace = true }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
once_cell = "1"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mongodb = "2"
thiserror = "1"
