[package]
name = "example-sse"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
futures-util = { version = "0.3", default-features = false }
salvo = { path = "../../crates/salvo", features = ["sse"] }
tokio = { version = "1", features = ["macros"] }
tokio-stream = { version = "0.1", features = ["net"] }
tracing = "0.1"
tracing-subscriber = "0.3"
