[package]
name = "salvo-tus"
version = { workspace = true }
edition = "2024"
rust-version = { workspace = true }
description = "TUS support for Salvo web framework"
readme = "./README.md"
license = { workspace = true }
documentation = "https://docs.rs/salvo-tus/"
homepage = { workspace = true }
repository = { workspace = true }
keywords = ["tus", "files-upload", "salvo"]
categories = ["network-programming", "asynchronous"]
authors = [
    "Tyrese Luo <tyreseluo@outlook.com>",
    "Salvo Maintainers"
]

[features]
default = []
# Store
file-store = []

[dependencies]
salvo_core    = { workspace = true, default-features = false }
thiserror     = { workspace = true }
base64        = { workspace = true }
tokio         = { workspace = true }
bytes         = { workspace = true }
serde         = { workspace = true, features = ["derive"] }
serde_json    = { workspace = true }
uuid          = { workspace = true, features = ["v4"]}
regex         = { workspace = true }
futures-core  = "0.3"
futures-util = { workspace = true }
chrono = { workspace = true }