[package]
name = "example-session-login"
version.workspace = true
edition.workspace = true
publish.workspace = true


[dependencies]
salvo = { workspace = true, features=["session"] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros"] }
tracing.workspace = true
tracing-subscriber.workspace = true