[package]
name = "example-sse-chat"
version.workspace = true
edition.workspace = true
publish.workspace = true


[dependencies]
futures-util.workspace = true
once_cell = "1"
parking_lot = "0.12"
salvo = { workspace = true, features = ["sse"] }
tokio = { workspace = true, features = ["macros"] }
tokio-stream = { workspace = true, features = ["net"] }
tracing.workspace = true
tracing-subscriber.workspace = true
