[package]
name = "salvo-postgres-seaorm"
version = "0.1.0"
edition = "2024"


[workspace]
members = [".", "migration"]

[dependencies]
migration = { path = "migration" }
anyhow = "1.0.100"
sea-orm = { version = "2.0.0-rc", features = ["with-chrono", "sqlx-postgres", "macros", "with-uuid", "with-time", "runtime-tokio", "runtime-tokio-native-tls", "runtime-tokio-rustls", "schema-sync", "entity-registry"] }
dotenvy = "0.15.7"
salvo = { version = "0.84.0", features = ["oapi", "affix-state", "anyhow", "jwt-auth", "test", "cors"] }
salvo-oapi = { version = "0.84.0", features = ["swagger-ui"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version="1.47.1", features= ["macros"]}
tracing = "0.1"
tracing-subscriber = "0.3" 
jsonwebtoken = "10.2.0"
time = "0.3.44"

argon2 = "0.5"
rand_core = "0.6"
password-hash = "0.5"
uuid = { version = "1.18.1", features = ["serde", "v4"] }
serde_json = "1.0.145"
chrono = { version = "0.4.42", features = ["serde"] }

[[bin]]
name = "salvo_postgres_seaorm"
path = "src/main.rs"


