[package]
name = "example-jwt-clerk"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
dotenvy = { workspace = true }
jsonwebtoken.workspace = true
salvo = { workspace = true, features = ["anyhow", "jwt-auth", "proxy"] }
serde = { workspace = true }
time.workspace = true
tokio = { workspace = true, features = ["macros"] }
tracing.workspace = true
tracing-subscriber.workspace = true
